DATA_SOURCE = {
    "name": "SkillsFuture Jobs-Skills Dataset",
    "release": "Q2 2026 curated demo subset",
    "note": (
        "The demo data mirrors the PRD examples and uses deterministic scoring. "
        "Full Excel ingestion can replace this subset without changing the UI model."
    ),
}


ROLES = [
    {
        "id": "backend-developer",
        "title": "Backend Developer",
        "family": "Software Engineering",
        "description": "Builds APIs, services, data pipelines, and cloud systems.",
        "skills": [
            "Python",
            "APIs",
            "SQL",
            "Docker",
            "Cloud Deployment",
            "Data Modelling",
            "System Design",
            "Testing",
            "Git",
        ],
    },
    {
        "id": "ai-engineer",
        "title": "AI Engineer",
        "family": "Artificial Intelligence",
        "description": "Builds machine learning and AI-enabled software systems.",
        "skills": [
            "Python",
            "APIs",
            "SQL",
            "Docker",
            "Machine Learning Fundamentals",
            "Model Evaluation",
            "Prompt Engineering",
            "Vector Databases",
            "Data Pipelines",
            "MLOps",
            "Responsible AI",
        ],
        "required": {
            "Machine Learning Fundamentals": 94,
            "Model Evaluation": 88,
            "Prompt Engineering": 81,
            "Vector Databases": 73,
            "MLOps": 69,
            "Responsible AI": 64,
            "Python": 91,
            "APIs": 70,
            "SQL": 66,
            "Docker": 62,
            "Data Pipelines": 58,
        },
    },
    {
        "id": "student",
        "title": "Student",
        "family": "Early Career",
        "description": "Has broad academic exposure and early project experience.",
        "skills": [
            "Research",
            "Communication",
            "Problem Solving",
            "Excel",
            "Presentation",
            "Basic Python",
            "Statistics Basics",
        ],
    },
    {
        "id": "data-analyst",
        "title": "Data Analyst",
        "family": "Data",
        "description": "Turns operational and business data into decisions.",
        "skills": [
            "SQL",
            "Excel",
            "Dashboarding",
            "Statistics Basics",
            "Data Cleaning",
            "Python",
            "Business Communication",
            "Data Storytelling",
            "Experiment Analysis",
        ],
        "required": {
            "SQL": 92,
            "Dashboarding": 87,
            "Data Cleaning": 84,
            "Python": 68,
            "Statistics Basics": 80,
            "Data Storytelling": 75,
            "Business Communication": 71,
            "Experiment Analysis": 58,
            "Excel": 76,
        },
    },
    {
        "id": "operations-executive",
        "title": "Operations Executive",
        "family": "Business Operations",
        "description": "Coordinates workflows, vendors, reporting, and process delivery.",
        "skills": [
            "Stakeholder Management",
            "Process Improvement",
            "Excel",
            "Vendor Coordination",
            "Risk Tracking",
            "Communication",
            "Project Coordination",
            "Reporting",
        ],
    },
    {
        "id": "product-manager",
        "title": "Product Manager",
        "family": "Product",
        "description": "Defines product outcomes, discovery, prioritisation, and delivery.",
        "skills": [
            "Stakeholder Management",
            "Communication",
            "Product Discovery",
            "Roadmapping",
            "User Research",
            "Experiment Analysis",
            "Prioritisation",
            "Analytics",
            "Go-to-Market Planning",
            "Project Coordination",
        ],
        "required": {
            "Product Discovery": 92,
            "Roadmapping": 85,
            "User Research": 81,
            "Prioritisation": 78,
            "Analytics": 73,
            "Stakeholder Management": 88,
            "Communication": 79,
            "Experiment Analysis": 64,
            "Go-to-Market Planning": 60,
            "Project Coordination": 57,
        },
    },
    {
        "id": "data-engineer",
        "title": "Data Engineer",
        "family": "Data",
        "description": "Builds reliable data systems, pipelines, warehouses, and tooling.",
        "skills": [
            "Python",
            "SQL",
            "Data Pipelines",
            "Cloud Deployment",
            "Docker",
            "Data Modelling",
            "Testing",
            "Workflow Orchestration",
            "APIs",
        ],
        "required": {
            "Python": 85,
            "SQL": 92,
            "Data Pipelines": 91,
            "Cloud Deployment": 70,
            "Docker": 66,
            "Data Modelling": 82,
            "Workflow Orchestration": 74,
            "APIs": 55,
            "Testing": 50,
        },
    },
    {
        "id": "mlops-engineer",
        "title": "MLOps Engineer",
        "family": "Artificial Intelligence",
        "description": "Ships, monitors, and maintains model-powered systems.",
        "skills": [
            "Python",
            "Docker",
            "Cloud Deployment",
            "APIs",
            "MLOps",
            "Model Evaluation",
            "Data Pipelines",
            "Monitoring",
            "Testing",
            "Responsible AI",
        ],
        "required": {
            "Python": 83,
            "Docker": 84,
            "Cloud Deployment": 82,
            "APIs": 62,
            "MLOps": 94,
            "Model Evaluation": 75,
            "Data Pipelines": 79,
            "Monitoring": 78,
            "Testing": 65,
            "Responsible AI": 56,
        },
    },
    {
        "id": "analytics-engineer",
        "title": "Analytics Engineer",
        "family": "Data",
        "description": "Bridges data engineering, metrics design, and analytics delivery.",
        "skills": [
            "SQL",
            "Data Modelling",
            "Dashboarding",
            "Data Pipelines",
            "Business Communication",
            "Testing",
            "Analytics",
            "Python",
            "Documentation",
        ],
        "required": {
            "SQL": 94,
            "Data Modelling": 87,
            "Dashboarding": 71,
            "Data Pipelines": 78,
            "Business Communication": 69,
            "Testing": 63,
            "Analytics": 82,
            "Python": 54,
            "Documentation": 52,
        },
    },
    {
        "id": "legal-assistant",
        "title": "Legal Assistant",
        "family": "Law",
        "description": "Supports legal research, case preparation, document handling, and client coordination.",
        "skills": [
            "Legal Research",
            "Document Review",
            "Client Communication",
            "Case Management",
            "Attention to Detail",
            "Writing",
            "Regulatory Awareness",
            "Calendar Management",
        ],
    },
    {
        "id": "legal-operations-analyst",
        "title": "Legal Operations Analyst",
        "family": "Law",
        "description": "Improves legal workflows with analytics, vendor management, and process design.",
        "skills": [
            "Legal Research",
            "Document Review",
            "Process Improvement",
            "Vendor Coordination",
            "Data Analysis",
            "Dashboarding",
            "Regulatory Awareness",
            "Stakeholder Management",
            "Contract Lifecycle Management",
        ],
        "required": {
            "Legal Research": 78,
            "Document Review": 72,
            "Process Improvement": 86,
            "Vendor Coordination": 65,
            "Data Analysis": 82,
            "Dashboarding": 70,
            "Regulatory Awareness": 74,
            "Stakeholder Management": 77,
            "Contract Lifecycle Management": 80,
        },
    },
    {
        "id": "graphic-designer",
        "title": "Graphic Designer",
        "family": "Creative",
        "description": "Creates visual assets, campaigns, and brand materials across channels.",
        "skills": [
            "Visual Design",
            "Brand Systems",
            "Typography",
            "Image Editing",
            "Client Communication",
            "Portfolio Storytelling",
            "Creative Direction",
            "Presentation",
        ],
    },
    {
        "id": "ux-designer",
        "title": "UX Designer",
        "family": "Creative",
        "description": "Designs useful digital experiences through research, prototyping, and testing.",
        "skills": [
            "User Research",
            "Prototyping",
            "Visual Design",
            "Information Architecture",
            "Usability Testing",
            "Portfolio Storytelling",
            "Stakeholder Management",
            "Product Discovery",
            "Accessibility",
        ],
        "required": {
            "User Research": 88,
            "Prototyping": 86,
            "Visual Design": 74,
            "Information Architecture": 78,
            "Usability Testing": 82,
            "Portfolio Storytelling": 80,
            "Stakeholder Management": 63,
            "Product Discovery": 66,
            "Accessibility": 72,
        },
    },
    {
        "id": "mechanical-engineer",
        "title": "Mechanical Engineer",
        "family": "Engineering",
        "description": "Designs, tests, and improves mechanical systems and manufactured products.",
        "skills": [
            "CAD Modelling",
            "Mechanical Design",
            "Technical Documentation",
            "Testing",
            "Manufacturing Processes",
            "Problem Solving",
            "Project Coordination",
            "Quality Control",
        ],
    },
    {
        "id": "robotics-engineer",
        "title": "Robotics Engineer",
        "family": "Engineering",
        "description": "Builds robotic systems using controls, sensors, software, and mechanical design.",
        "skills": [
            "Mechanical Design",
            "CAD Modelling",
            "Python",
            "Control Systems",
            "Sensors",
            "Embedded Systems",
            "Testing",
            "Technical Documentation",
            "System Integration",
        ],
        "required": {
            "Mechanical Design": 82,
            "CAD Modelling": 76,
            "Python": 70,
            "Control Systems": 90,
            "Sensors": 84,
            "Embedded Systems": 86,
            "Testing": 65,
            "Technical Documentation": 58,
            "System Integration": 80,
        },
    },
    {
        "id": "sustainability-coordinator",
        "title": "Sustainability Coordinator",
        "family": "Sustainability",
        "description": "Coordinates ESG reporting, environmental initiatives, and stakeholder programmes.",
        "skills": [
            "Stakeholder Management",
            "Reporting",
            "Project Coordination",
            "Research",
            "Communication",
            "Data Analysis",
            "Sustainability Reporting",
            "Regulatory Awareness",
        ],
    },
    {
        "id": "climate-data-analyst",
        "title": "Climate Data Analyst",
        "family": "Sustainability",
        "description": "Uses data to evaluate climate risk, sustainability metrics, and environmental impact.",
        "skills": [
            "Data Analysis",
            "Statistics Basics",
            "Python",
            "Dashboarding",
            "Sustainability Reporting",
            "Geospatial Analysis",
            "Regulatory Awareness",
            "Data Storytelling",
            "Research",
        ],
        "required": {
            "Data Analysis": 90,
            "Statistics Basics": 82,
            "Python": 74,
            "Dashboarding": 72,
            "Sustainability Reporting": 85,
            "Geospatial Analysis": 78,
            "Regulatory Awareness": 68,
            "Data Storytelling": 70,
            "Research": 64,
        },
    },
]


def role_index():
    return {role["id"]: role for role in ROLES}
